version: '3.8'
services:
  web:
    container_name: php_web
    image: php:8.2-apache
    ports:
      - "6400:80"
    volumes:
      - /var/www/html:/var/www/html
    networks:
      - webnet

  db:
    container_name: mysql_web
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_DATABASE=database_web
      - MYSQL_ROOT_PASSWORD=RootP@ss123!
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
---
version: '3.8'
services:
  httpd_service:
    image: httpd:latest
    container_name: httpd
    ports:
      - "5001:80"  # Maps port 80 of the container to port 5001 of the host
    volumes:
      - /opt/data:/usr/local/apache2/htdocs  # Maps /opt/data on host to container's /usr/local/apache2/htdocs
    restart: always  # Ensure the container restarts automatically if it fails
    networks:
      - webnet
      
