---
- name: Replace text in files on app servers
  hosts: all
  become: yes
  tasks:

    - name: Replace xFusionCorp with Nautilus on app server 1
      replace:
        path: /opt/dba/blog.txt
        regexp: 'xFusionCorp'
        replace: 'Nautilus'
      when: inventory_hostname == 'stapp01'

    - name: Replace Nautilus with KodeKloud on app server 2
      replace:
        path: /opt/dba/story.txt
        regexp: 'Nautilus'
        replace: 'KodeKloud'
      when: inventory_hostname == 'stapp02'

    - name: Replace KodeKloud with xFusionCorp Industries on app server 3
      replace:
        path: /opt/dba/media.txt
        regexp: 'KodeKloud'
        replace: 'xFusionCorp Industries'
      when: inventory_hostname == 'stapp03'
